apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: employee-rest-service
  labels:
    run: employee-rest-service
spec:
  replicas: 1
  #strategy:
  #  rollingUpdate:
  #    maxSurge: 1
  #    maxUnavailable: 1
  #  type: RollingUpdate
  template:
    metadata:
      labels:
        run: employee-rest-service
    spec:
      containers:
      - image: bluezd/java-maven-sonar:$BUILD_NUMBER
        imagePullPolicy: Always 
        name: employee-rest-service 
        ports:
        - containerPort: 8080 
          protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: employee-rest-service-svc
spec:
    type: NodePort
    ports:
    - name: http
      port: 8081
      targetPort: 8080
      protocol: TCP
    selector:
      run: employee-rest-service
